install_dependencies: &install_dependencies
  name: Install Dependencies
  command: |
    pip install -r requirements/base.txt
    pip install -r requirements/test.txt

version: 2
jobs:
  python27:
    docker:
      - image: python:2.7
    working_directory: "~/braspag/braspag-py27/"
    steps:
      - checkout
      - restore_cache:
          keys:
            - pip-{{ .Branch }}
            - pip-master
      - run:
          <<: *install_dependencies
      - save_cache:
          key: pip-{{ .Branch }}
          paths:
            - "~/.cache/pip"
      - run:
          name: Run Tests
          command: make test
  python37:
    docker:
      - image: python:3.7
      working_directory: "~/braspag/braspag-py37/"
      steps:
        - checkout
        - restore_cache:
            keys:
              - pip-{{ .Branch }}
              - pip-master
        - run:
            <<: *install_dependencies
        - save_cache:
            key: pip-{{ .Branch }}
            paths:
              - "~/.cache/pip"
        - run:
            name: Run Tests
            command: make test
workflows:
  version: 2
  build_and_test:
    jobs:
      - python27
      - python37
